# This file contains the information needed for Shopify to authenticate
# requests and edit/update your remote theme files.
#
# 1. Set up a private app (https://help.shopify.com/api/guides/api-credentials#generate-private-app-credentials)
#    with "Read and write" permissions for "Theme templates and theme assets".
# 2. Replace the required variables for each environment below.
#
# password, theme_id, and store variables are required.
#
# For more information on this config file:
#   Configuration variables | http://shopify.github.io/themekit/configuration/
#   Ignore patterns | http://shopify.github.io/themekit/ignores/
# 46ea5c2c7c6572828054163b80f8ea9c5479969e
---

development:
  password: c912420eee9390f91cb896854699b596
  theme_id: "25455493177"
  store: odyssei-clothing-llc.myshopify.com
  #proxy: https://localhost:3001
  ignore_files:
    - "*.gif"
    - "*.jpg"
    - config/settings_data.json
production:
  password: c912420eee9390f91cb896854699b596
  theme_id: "25455493177"
  store: odyssei-clothing-llc.myshopify.com
  timeout: 60s
  readonly: false
test:
  password: c912420eee9390f91cb896854699b596
  theme_id: "25455493177"
  store: odyssei-clothing-llc.myshopify.com
  ignores: ignore.txt
